#!/bin/sh

. ~/dotfiles/suckless/dwmblocks/scripts/themes/onedark.sh

# Show wifi 📶 and percent strength or 📡 if none.
# Show 🌐 if connected to ethernet or ❎ if none.
# Show 🔒 if a vpn connection is active
if grep -xq 'up' /sys/class/net/w*/operstate 2>/dev/null ; then
	wifiicon="$(awk '/^\s*w/ { print " ", int($3 * 100 / 70) "% " }' /proc/net/wireless)"
elif grep -xq 'up' /sys/class/net/e*/operstate 2>/dev/null ; then
	grep -xq '0x1003' /sys/class/net/e*/flags && wifiicon=" eth"
elif grep -xq 'down' /sys/class/net/e*/operstate 2>/dev/null ; then
	grep -xq '0x1003' /sys/class/net/e*/flags && wifiicon="睊  disconnected"
fi

printf "^c$orange^ %s%s%s\n" "$wifiicon" "$(sed "s/down//;s/up/🌐/" /sys/class/net/e*/operstate 2>/dev/null)" "$(sed "s/.*/🔒/" /sys/class/net/tun*/operstate 2>/dev/null)"
