# ---- Video renderer ----
vo=gpu-next
gpu-api=vulkan
hwdec=auto-safe

# ---- Output / dither ----
dither-depth=auto

# ---- HDR / color management ----
target-colorspace-hint=yes
target-peak=400
target-contrast=1000

# ---- Scalers ----
scale=ewa_lanczossharp
cscale=ewa_lanczossharp
dscale=mitchell
scale-antiring=0.7
cscale-antiring=0.7

# ---- Debanding ----
deband=no

# ---- YouTube ----
ytdl-format=bestvideo[height<=?1440]+bestaudio/best
script-opts=ytdl_hook-ytdl_path=yt-dlp
ytdl-raw-options=cookies-from-browser=firefox

# ---- Audio / misc ----
volume=50
no-audio-display
keep-open=yes
save-position-on-quit=yes
