#!/usr/bin/env bash
# Rebuild ~/.pi from this repo on a fresh machine.
#
#   ~/dotfiles/config/pi/bootstrap.sh              link config, install, patch
#   ~/dotfiles/config/pi/bootstrap.sh --check      report drift, change nothing
#   ~/dotfiles/config/pi/bootstrap.sh --sync-back  pull live changes into repo
#
# Config is symlinked out of the repo so edits here are edits there.
#
# Packages are NOT pinned by a lockfile: settings.json `packages[]` is the
# source of truth and step 4 runs `pi install` for each entry. Pin a version
# in packages[] (e.g. npm:pi-zentui@0.25.0) when something depends on it.
# pi's own lockfile (npm/, --legacy-peer-deps) stays machine-local.
#
# settings.json is a third case. It mixes shared config with per-machine
# choices, so it is MERGED in both directions: the repo owns the shared keys,
# this machine owns LOCAL_KEYS (provider, model, thinking level). The model
# name never enters the repo — different machines run different providers.
set -uo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PI="${PI_CODING_AGENT_DIR:-$HOME/.pi/agent}"
CHECK=0; SYNC_BACK=0
case "${1:-}" in
  --check)     CHECK=1 ;;
  --sync-back) SYNC_BACK=1 ;;
esac

say() { printf '%s\n' "$*"; }
ok()  { printf '  ok      %s\n' "$*"; }
act() { printf '  %s %s\n' "$([ $CHECK -eq 1 ] && echo 'DRIFT  ' || echo "${VERB:-link}   ")" "$*"; }

# Files pi/npm never write — safe to symlink at the repo.
LINKS=(
  AGENTS.md zentui.json pi-fff.json subagents.json
  base16-to-pi-theme.py patches
)
# Directories linked entry-by-entry rather than whole, because they also hold
# files this repo deliberately does not track:
#   extensions/ -> litellm-auto.ts (gitignored, per-machine)
#   themes/     -> stylix.json (generated by home-manager into /nix/store)
# Linking the directory itself would delete those.
PER_ENTRY=( extensions themes skills )
# settings.json is neither linked nor copied wholesale: it holds BOTH shared
# config (packages, theme, compaction) and per-machine choices. These keys are
# per-machine and never enter the repo — a different box runs a different
# provider, and the model name is not public information.
LOCAL_KEYS='["defaultProvider","defaultModel","defaultThinkingLevel","lastChangelogVersion"]'

say "pi bootstrap: $REPO -> $PI"

# --- 0. sync-back ---------------------------------------------------------
# Live -> repo, for the files pi/npm rewrite in place. LOCAL_KEYS are stripped
# on the way out, so a model name physically cannot reach the repo even if you
# run this right after switching providers. Symlinked files need no sync-back:
# editing them already edits the repo.
if [ $SYNC_BACK -eq 1 ]; then
  say "sync-back: $PI -> $REPO"
  if [ -f "$PI/settings.json" ]; then
    jq --argjson keys "$LOCAL_KEYS" \
       'delpaths([$keys[] | [.]])' "$PI/settings.json" > "$REPO/agent/settings.json" \
      || { say "  jq strip failed"; exit 1; }
    ok "settings.json (local keys stripped)"
  fi
  say ""
  say "Review with: git -C \"$REPO\" diff ."
  exit 0
fi

# --- 1. prerequisites -----------------------------------------------------
command -v pi  >/dev/null || { say "pi not on PATH — install it first"; exit 1; }
command -v npm >/dev/null || { say "npm not on PATH"; exit 1; }

mkdir -p "$PI/npm" "$PI/themes"

# --- 2. symlinked config --------------------------------------------------
say "config:"
for f in "${LINKS[@]}"; do
  src="$REPO/agent/$f"; dst="$PI/$f"
  [ -e "$src" ] || continue
  if [ -L "$dst" ] && [ "$(readlink -f "$dst")" = "$(readlink -f "$src")" ]; then
    ok "$f"; continue
  fi
  act "$f"
  [ $CHECK -eq 1 ] && continue
  rm -rf "$dst"; ln -s "$src" "$dst"
done

# Entry-by-entry: only paths this repo tracks are replaced. Anything else
# already in the directory is left exactly as it is.
for d in "${PER_ENTRY[@]}"; do
  [ -d "$REPO/agent/$d" ] || continue
  mkdir -p "$PI/$d"
  for src in "$REPO/agent/$d"/*; do
    [ -e "$src" ] || continue
    dst="$PI/$d/$(basename "$src")"
    if [ -L "$dst" ] && [ "$(readlink -f "$dst")" = "$(readlink -f "$src")" ]; then
      ok "$d/$(basename "$src")"; continue
    fi
    act "$d/$(basename "$src")"
    [ $CHECK -eq 1 ] && continue
    rm -rf "$dst"; ln -s "$src" "$dst"
  done
done

# --- 3b. settings.json (merged, never overwritten) -------------------------
# Repo supplies the shared keys; whatever this machine already chose for
# LOCAL_KEYS is carried over untouched. A fresh machine simply has none, and
# pi picks a model on first run.
say "settings.json (merge, local keys preserved):"
SRC_S="$REPO/agent/settings.json"; DST_S="$PI/settings.json"
if [ ! -f "$SRC_S" ]; then
  say "  missing $SRC_S"
elif [ ! -f "$DST_S" ]; then
  act "settings.json (new)"
  [ $CHECK -eq 0 ] && cp -p "$SRC_S" "$DST_S"
else
  merged="$(jq -s --argjson keys "$LOCAL_KEYS" \
      '.[0] * (.[1] | with_entries(select(.key as $k | $keys | index($k))))' \
      "$SRC_S" "$DST_S")" || { say "  jq merge failed"; exit 1; }
  if [ "$merged" = "$(cat "$DST_S")" ]; then
    ok "settings.json"
  else
    act "settings.json"
    [ $CHECK -eq 0 ] && printf '%s\n' "$merged" > "$DST_S"
  fi
  for k in $(printf '%s' "$LOCAL_KEYS" | jq -r '.[]'); do
    v="$(jq -r --arg k "$k" '.[$k] // empty' "$DST_S")"
    [ -n "$v" ] && printf '  kept    %s = %s (local)\n' "$k" "$v"
  done
fi

# --- 4. packages ----------------------------------------------------------
# One `pi install` per missing/mismatched packages[] entry. pi resolves peers
# its own way (--legacy-peer-deps), so we never run npm here directly.
# Installed-but-unpinned packages are left alone: upgrading is `pi update`.
say "packages (from settings.json):"
spec_name() { local s="${1#npm:}" at=""; [ "${s:0:1}" = "@" ] && { at="@"; s="${s:1}"; }
              printf '%s%s' "$at" "${s%%@*}"; }
spec_ver()  { local s="${1#npm:}"; s="${s#@}"; [ "${s#*@}" != "$s" ] && printf '%s' "${s#*@}"; }
while IFS= read -r spec; do
  [ -n "$spec" ] || continue
  case "$spec" in npm:*) ;; *)
    [ $CHECK -eq 1 ] && { ok "$spec (non-npm, not checked)"; continue; }
    pi install "$spec" >/dev/null 2>&1 && ok "$spec" || say "  FAILED  $spec"; continue ;;
  esac
  name="$(spec_name "$spec")"; want="$(spec_ver "$spec")"
  pj="$PI/npm/node_modules/$name/package.json"
  have="$( [ -f "$pj" ] && jq -r .version "$pj")"
  if [ -n "$have" ] && { [ -z "$want" ] || [ "$have" = "$want" ]; }; then
    ok "$spec ($have)"; continue
  fi
  VERB=install act "$spec${have:+ (have $have)}"
  [ $CHECK -eq 1 ] && continue
  pi install "$spec" >/dev/null 2>&1 || { say "  FAILED  pi install $spec"; exit 1; }
done < <(jq -r '.packages[]? | if type=="string" then . else .source end' "$PI/settings.json")

# --- 5. the silent one ----------------------------------------------------
# The zentui patch lives INSIDE node_modules, which is untracked. A fresh
# install yields unpatched zentui with no error — percentages instead of real
# token counts in the footer. This step is why the script exists.
say "patches:"
if [ -x "$PI/patches/apply-zentui-patch.sh" ]; then
  if [ $CHECK -eq 1 ]; then
    "$PI/patches/apply-zentui-patch.sh" --check | sed 's/^/  /'
  else
    "$PI/patches/apply-zentui-patch.sh" | sed 's/^/  /'
  fi
else
  say "  patches/apply-zentui-patch.sh missing"
fi

# --- 6. what this script cannot do ----------------------------------------
cat <<EOF

Not handled here (secrets / per-machine — see SETUP.md):
  $PI/auth.json          pi auth login
  $PI/models.json        provider config incl. LAN IP
  $PI/models-store.json  xai oauth token store
  $PI/mcp.json           MCP servers; carries inline credentials
                         (rebuild from SETUP.md step 5)

Per-machine model choice (never in the repo):
  $PI/model-state.json   written by extensions/remember-model.ts
  Pick a model/thinking level with Enter — it is remembered per machine, and
  each model keeps its own thinking level. Avoid Ctrl+S in /model or /thinking:
  that writes defaultModel etc. into settings.json (harmless — --sync-back
  strips them — but it duplicates the choice).
EOF
