#!/usr/bin/env bash
# Rebuild ~/.pi from this repo on a fresh machine.
#
#   ~/dotfiles/config/pi/bootstrap.sh            link config, install, patch
#   ~/dotfiles/config/pi/bootstrap.sh --check    report drift, change nothing
#
# Config is symlinked out of the repo so edits here are edits there — EXCEPT
# for the files pi and npm rewrite themselves (settings.json, package.json,
# package-lock.json). Those are copied: a read-only symlink into the repo
# makes `pi install` and `npm install` fail. Re-run sync-back after changing
# them, or they drift out of the repo silently.
set -uo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PI="${PI_CODING_AGENT_DIR:-$HOME/.pi/agent}"
CHECK=0
[ "${1:-}" = "--check" ] && CHECK=1

say() { printf '%s\n' "$*"; }
ok()  { printf '  ok      %s\n' "$*"; }
act() { printf '  %s %s\n' "$([ $CHECK -eq 1 ] && echo 'DRIFT  ' || echo 'link   ')" "$*"; }

# Files pi/npm never write — safe to symlink at the repo.
LINKS=(
  AGENTS.md zentui.json pi-fff.json subagents.json
  base16-to-pi-theme.py patches
)
# Directories linked entry-by-entry rather than whole, because they also hold
# files this repo deliberately does not track:
#   extensions/ -> litellm-auto.ts (gitignored, per-machine)
#   themes/     -> stylix.json (generated by home-manager into /nix/store)
# Linking the directory itself would delete those.
PER_ENTRY=( extensions themes skills )
# Files pi/npm rewrite in place — must be real files.
COPIES=( settings.json npm/package.json npm/package-lock.json )

say "pi bootstrap: $REPO -> $PI"

# --- 1. prerequisites -----------------------------------------------------
command -v pi  >/dev/null || { say "pi not on PATH — install it first"; exit 1; }
command -v npm >/dev/null || { say "npm not on PATH"; exit 1; }

mkdir -p "$PI/npm" "$PI/themes"

# --- 2. symlinked config --------------------------------------------------
say "config:"
for f in "${LINKS[@]}"; do
  src="$REPO/agent/$f"; dst="$PI/$f"
  [ -e "$src" ] || continue
  if [ -L "$dst" ] && [ "$(readlink -f "$dst")" = "$(readlink -f "$src")" ]; then
    ok "$f"; continue
  fi
  act "$f"
  [ $CHECK -eq 1 ] && continue
  rm -rf "$dst"; ln -s "$src" "$dst"
done

# Entry-by-entry: only paths this repo tracks are replaced. Anything else
# already in the directory is left exactly as it is.
for d in "${PER_ENTRY[@]}"; do
  [ -d "$REPO/agent/$d" ] || continue
  mkdir -p "$PI/$d"
  for src in "$REPO/agent/$d"/*; do
    [ -e "$src" ] || continue
    dst="$PI/$d/$(basename "$src")"
    if [ -L "$dst" ] && [ "$(readlink -f "$dst")" = "$(readlink -f "$src")" ]; then
      ok "$d/$(basename "$src")"; continue
    fi
    act "$d/$(basename "$src")"
    [ $CHECK -eq 1 ] && continue
    rm -rf "$dst"; ln -s "$src" "$dst"
  done
done

# --- 3. copied (agent-writable) config ------------------------------------
say "writable config (copied, not linked):"
for f in "${COPIES[@]}"; do
  src="$REPO/agent/$f"; dst="$PI/$f"
  [ -e "$src" ] || continue
  if [ -f "$dst" ] && cmp -s "$src" "$dst"; then ok "$f"; continue; fi
  act "$f"
  [ $CHECK -eq 1 ] && continue
  mkdir -p "$(dirname "$dst")"; cp -p "$src" "$dst"
done

# --- 4. extensions --------------------------------------------------------
if [ $CHECK -eq 0 ]; then
  say "npm packages:"
  ( cd "$PI/npm" && npm ci ) || { say "npm ci failed"; exit 1; }
fi

# --- 5. the silent one ----------------------------------------------------
# The zentui patch lives INSIDE node_modules, which is untracked. A fresh
# npm ci yields unpatched zentui with no error — percentages instead of real
# token counts in the footer. This step is why the script exists.
say "patches:"
if [ -x "$PI/patches/apply-zentui-patch.sh" ]; then
  if [ $CHECK -eq 1 ]; then
    "$PI/patches/apply-zentui-patch.sh" --check | sed 's/^/  /'
  else
    "$PI/patches/apply-zentui-patch.sh" | sed 's/^/  /'
  fi
else
  say "  patches/apply-zentui-patch.sh missing"
fi

# --- 6. what this script cannot do ----------------------------------------
cat <<EOF

Not handled here (secrets / per-machine — see SETUP.md):
  $PI/auth.json          pi auth login
  $PI/models.json        provider config incl. LAN IP
  $PI/models-store.json  xai oauth token store
  $PI/mcp.json           MCP servers; carries inline credentials
                         (rebuild from SETUP.md step 5)
  $PI/extensions/litellm-auto.ts
                         rebuild from docs/extensions/litellm-auto.md
EOF
