# Inserts a blank line between shell prompts
add_newline = false 


# format = "\\[$username@$hostname $directory \\] \\$ "

[line_break]
disabled=true

# Replace the "❯" symbol in the prompt with "➜"
[character]                            # The name of the module we are configuring is "character"
#success_symbol = "[➜](bold green) "     # The "success_symbol" segment is being set to "➜" with the color "bold green"
# success_symbol = "[❯](bold green) "     
# # Disable the package module, hiding it from the prompt completely
# success_symbol = "[\\$](bold green) "
# success_symbol = "[\\$](bold green) "
#[package]
#disabled = true
[git_status]
# disabled=true
# [username]
# format = " [$user]($style) "
# show_always = true

# [hostname]
# format = " [$hostname]($style) "
# ssh_only = false

# # Replace slashes with spaces in directory
# [directory]
# format = " [$path]($style) "
# substitutions = { "/" = " " }
[nodejs]
disabled=true