pragma Singleton
pragma ComponentBehavior: Bound

import QtQuick

// Theme singleton for the Hermes desktop app.
//
// The chat components were written against DMS's Theme singleton (Material You
// tokens). This reimplements the same token surface; every derived token
// (hover, pressed, alpha fills) is computed from the base palette, so the
// accents stay coherent.
//
// The base palette is seeded with gruvbox-material defaults, then — if the
// home-manager module generated ~/.config/HermesApp/colors.json from the active
// stylix scheme — overridden to match the system theme at startup. With no
// such file (e.g. running standalone), the bundled gruvbox defaults stand.
QtObject {
    id: theme

    // ── Base palette (gruvbox-material defaults; may be overridden by stylix) ──
    property color _bg0:  "#282828"
    property color _bg1:  "#32302f"
    property color _bg2:  "#3c3836"
    property color _bg3:  "#45403d"
    property color _bg4:  "#504945"
    property color _fg0:  "#d4be98"
    property color _fgDim: "#a89984"
    property color _gray: "#928374"

    property color _blue:   "#7daea3"
    property color _aqua:   "#89b482"
    property color _purple: "#d3869b"
    property color _red:    "#ea6962"
    property color _green:  "#a9b665"
    property color _yellow: "#d8a657"

    // ── stylix override ────────────────────────────────────────
    // main.py reads ~/.config/HermesApp/colors.json (generated by the
    // home-manager module from the active stylix scheme) and exposes it as the
    // `stylixColors` context property. base24 slots map onto the palette above;
    // the upper surface shades (_bg3/_bg4, used as light surfaces and borders)
    // are lightened from base02 so they read well regardless of scheme.
    Component.onCompleted: _loadStylixColors()

    function _loadStylixColors() {
        if (typeof stylixColors === "undefined" || !stylixColors || !stylixColors.base00)
            return
        const c = stylixColors
        _bg0 = c.base00
        _bg1 = c.base01
        _bg2 = c.base02
        _bg3 = Qt.lighter(c.base02, 1.35)
        _bg4 = Qt.lighter(c.base02, 1.7)
        _fg0 = c.base05
        _fgDim = c.base04
        _gray = c.base03
        _red = c.base08
        _yellow = c.base0A
        _green = c.base0B
        _aqua = c.base0C
        _blue = c.base0D
        _purple = c.base0E
    }

    // ── Spacing & sizing ───────────────────────────────────────
    readonly property int spacingXS: 4
    readonly property int spacingS: 8
    readonly property int spacingM: 12
    readonly property int spacingL: 16
    readonly property int iconSize: 20
    readonly property int cornerRadius: 12

    readonly property int fontSizeSmall: 12
    readonly property int fontSizeMedium: 14
    readonly property int fontSizeLarge: 18

    // ── Text ───────────────────────────────────────────────────
    readonly property color surfaceText: _fg0
    readonly property color surfaceTextMedium: _fgDim
    readonly property color surfaceVariantText: _gray

    // ── Surfaces ───────────────────────────────────────────────
    readonly property color surfaceContainer: _bg1
    readonly property color surfaceContainerHigh: _bg2
    readonly property color surfaceContainerHighest: _bg3
    readonly property color surfaceVariant: _bg4
    readonly property color surfaceVariantAlpha: Qt.rgba(_bg4.r, _bg4.g, _bg4.b, 0.35)
    readonly property color surfaceHover: Qt.rgba(1, 1, 1, 0.06)

    // ── Primary accent ─────────────────────────────────────────
    readonly property color primary: _blue
    readonly property color primaryText: _bg0
    readonly property color onPrimary: _bg0
    readonly property color primaryPressed: Qt.darker(_blue, 1.2)
    readonly property color primaryBackground: Qt.rgba(_blue.r, _blue.g, _blue.b, 0.15)
    readonly property color primarySelected: Qt.rgba(_blue.r, _blue.g, _blue.b, 0.22)

    // ── Semantic accents ───────────────────────────────────────
    readonly property color tertiary: _purple
    readonly property color error: _red
    readonly property color errorPressed: Qt.rgba(_red.r, _red.g, _red.b, 0.25)
    readonly property color success: _green
    readonly property color warning: _yellow

    // ── Outlines ───────────────────────────────────────────────
    readonly property color outlineVariant: _bg3
    readonly property color outlineMedium: _bg4
}
