;;; treesitter-face-fix.el --- Fix treesitter face timing issue in Emacs themes

;; Author: Generated by AI assistant
;; Created: 2026-03-05
;; Version: 1.0
;; Keywords: faces, treesitter, themes

;;; Commentary:
;; This file solves the Emacs treesitter face timing issue where treesitter faces
;; (tree-sitter-hl-face:* and treesit-font-lock:*) are created dynamically when
;; `treesit-font-lock-mode` is first activated, not when themes load.
;;
;; Theme face definitions via `custom-theme-set-faces` are ignored if the faces
;; don't exist yet, causing syntax elements to appear as white text.
;;
;; This solution:
;; 1. Creates treesitter faces if they don't exist
;; 2. Applies theme colors to treesitter faces after theme loads
;; 3. Works with any theme that defines standard doom-theme color variables
;;
;; Usage:
;; Add to your Emacs config:
;; (load "~/dotfiles/emacs/treesitter-face-fix.el")

;;; Code:

(require 'doom-themes)

(defvar treesitter-face-fix--color-mapping
  '((green   . "green")
    (red     . "red")
    (cyan    . "cyan")
    (magenta . "magenta")
    (yellow  . "yellow")
    (orange  . "orange")
    (blue    . "blue")
    (grey    . "grey")
    (fg      . "fg")
    (comments . "comments"))
  "Mapping from theme color symbols to doom-color function names.")

(defun treesitter-face-fix--get-theme-color (color-symbol)
  "Get color value for COLOR-SYMBOL from current theme."
  (condition-case nil
      (doom-color color-symbol)
    (error
     (message "treesitter-face-fix: Could not get color for %s" color-symbol)
     nil)))

(defun treesitter-face-fix--create-treesitter-faces ()
  "Create treesitter faces if they don't exist."
  (let ((face-names
         '("tree-sitter-hl-face:annotation"
           "tree-sitter-hl-face:attribute"
           "tree-sitter-hl-face:boolean"
           "tree-sitter-hl-face:character"
           "tree-sitter-hl-face:character.special"
           "tree-sitter-hl-face:comment"
           "tree-sitter-hl-face:conditional"
           "tree-sitter-hl-face:constant"
           "tree-sitter-hl-face:constant.builtin"
           "tree-sitter-hl-face:constant.macro"
           "tree-sitter-hl-face:constructor"
           "tree-sitter-hl-face:field"
           "tree-sitter-hl-face:float"
           "tree-sitter-hl-face:function"
           "tree-sitter-hl-face:function.call"
           "tree-sitter-hl-face:function.macro"
           "tree-sitter-hl-face:keyword"
           "tree-sitter-hl-face:keyword.conditional"
           "tree-sitter-hl-face:keyword.function"
           "tree-sitter-hl-face:keyword.operator"
           "tree-sitter-hl-face:keyword.return"
           "tree-sitter-hl-face:label"
           "tree-sitter-hl-face:method"
           "tree-sitter-hl-face:method.call"
           "tree-sitter-hl-face:namespace"
           "tree-sitter-hl-face:number"
           "tree-sitter-hl-face:operator"
           "tree-sitter-hl-face:parameter"
           "tree-sitter-hl-face:parameter.reference"
           "tree-sitter-hl-face:property"
           "tree-sitter-hl-face:punctuation.bracket"
           "tree-sitter-hl-face:punctuation.delimiter"
           "tree-sitter-hl-face:repeat"
           "tree-sitter-hl-face:string"
           "tree-sitter-hl-face:string.escape"
           "tree-sitter-hl-face:string.regex"
           "tree-sitter-hl-face:string.special"
           "tree-sitter-hl-face:type"
           "tree-sitter-hl-face:type.builtin"
           "tree-sitter-hl-face:type.definition"
           "tree-sitter-hl-face:variable"
           "tree-sitter-hl-face:variable.builtin"
           "tree-sitter-hl-face:variable.parameter"
           "treesit-font-lock:annotation"
           "treesit-font-lock:attribute"
           "treesit-font-lock:boolean"
           "treesit-font-lock:character"
           "treesit-font-lock:character.special"
           "treesit-font-lock:comment"
           "treesit-font-lock:conditional"
           "treesit-font-lock:constant"
           "treesit-font-lock:constant.builtin"
           "treesit-font-lock:constant.macro"
           "treesit-font-lock:constructor"
           "treesit-font-lock:field"
           "treesit-font-lock:float"
           "treesit-font-lock:function"
           "treesit-font-lock:function.call"
           "treesit-font-lock:function.macro"
           "treesit-font-lock:keyword"
           "treesit-font-lock:keyword.conditional"
           "treesit-font-lock:keyword.function"
           "treesit-font-lock:keyword.operator"
           "treesit-font-lock:keyword.return"
           "treesit-font-lock:label"
           "treesit-font-lock:method"
           "treesit-font-lock:method.call"
           "treesit-font-lock:namespace"
           "treesit-font-lock:number"
           "treesit-font-lock:operator"
           "treesit-font-lock:parameter"
           "treesit-font-lock:parameter.reference"
           "treesit-font-lock:property"
           "treesit-font-lock:punctuation.bracket"
           "treesit-font-lock:punctuation.delimiter"
           "treesit-font-lock:repeat"
           "treesit-font-lock:string"
           "treesit-font-lock:string.escape"
           "treesit-font-lock:string.regex"
           "treesit-font-lock:string.special"
           "treesit-font-lock:type"
           "treesit-font-lock:type.builtin"
           "treesit-font-lock:type.definition"
           "treesit-font-lock:variable"
           "treesit-font-lock:variable.builtin"
           "treesit-font-lock:variable.parameter")))
    (dolist (face-name face-names)
      (let ((face-sym (intern face-name)))
        (unless (facep face-sym)
          (make-empty-face face-sym)
          (message "treesitter-face-fix: Created face %s" face-name))))))

(defun treesitter-face-fix--apply-gruvbox-material-faces ()
  "Apply gruvbox-material theme colors to treesitter faces."
  (let ((colors '((green   . green)
                  (red     . red)
                  (cyan    . cyan)
                  (magenta . magenta)
                  (yellow  . yellow)
                  (orange  . orange)
                  (blue    . blue)
                  (grey    . grey)
                  (fg      . fg)
                  (comments . comments))))
    
    ;; Create face specifications based on doom-gruvbox-material-theme.el
    (custom-set-faces
     ;; tree-sitter-hl-face:*
     `(tree-sitter-hl-face:annotation :foreground ,(treesitter-face-fix--get-theme-color 'magenta))
     `(tree-sitter-hl-face:attribute :foreground ,(treesitter-face-fix--get-theme-color 'magenta))
     `(tree-sitter-hl-face:boolean :foreground ,(treesitter-face-fix--get-theme-color 'magenta))
     `(tree-sitter-hl-face:character :foreground ,(treesitter-face-fix--get-theme-color 'cyan))
     `(tree-sitter-hl-face:character.special :foreground ,(treesitter-face-fix--get-theme-color 'cyan))
     `(tree-sitter-hl-face:comment :foreground ,(treesitter-face-fix--get-theme-color 'comments))
     `(tree-sitter-hl-face:conditional :foreground ,(treesitter-face-fix--get-theme-color 'red))
     `(tree-sitter-hl-face:constant :foreground ,(treesitter-face-fix--get-theme-color 'fg))
     `(tree-sitter-hl-face:constant.builtin :foreground ,(treesitter-face-fix--get-theme-color 'magenta) :slant italic)
     `(tree-sitter-hl-face:constant.macro :foreground ,(treesitter-face-fix--get-theme-color 'magenta) :slant italic)
     `(tree-sitter-hl-face:constructor :foreground ,(treesitter-face-fix--get-theme-color 'green) :weight bold)
     `(tree-sitter-hl-face:field :foreground ,(treesitter-face-fix--get-theme-color 'blue))
     `(tree-sitter-hl-face:float :foreground ,(treesitter-face-fix--get-theme-color 'magenta))
     `(tree-sitter-hl-face:function :foreground ,(treesitter-face-fix--get-theme-color 'green) :weight bold)
     `(tree-sitter-hl-face:function.call :foreground ,(treesitter-face-fix--get-theme-color 'green) :weight bold)
     `(tree-sitter-hl-face:function.macro :foreground ,(treesitter-face-fix--get-theme-color 'green) :weight bold)
     `(tree-sitter-hl-face:keyword :foreground ,(treesitter-face-fix--get-theme-color 'red))
     `(tree-sitter-hl-face:keyword.conditional :foreground ,(treesitter-face-fix--get-theme-color 'red))
     `(tree-sitter-hl-face:keyword.function :foreground ,(treesitter-face-fix--get-theme-color 'red))
     `(tree-sitter-hl-face:keyword.operator :foreground ,(treesitter-face-fix--get-theme-color 'orange))
     `(tree-sitter-hl-face:keyword.return :foreground ,(treesitter-face-fix--get-theme-color 'red))
     `(tree-sitter-hl-face:label :foreground ,(treesitter-face-fix--get-theme-color 'orange))
     `(tree-sitter-hl-face:method :foreground ,(treesitter-face-fix--get-theme-color 'green) :weight bold)
     `(tree-sitter-hl-face:method.call :foreground ,(treesitter-face-fix--get-theme-color 'green) :weight bold)
     `(tree-sitter-hl-face:namespace :foreground ,(treesitter-face-fix--get-theme-color 'yellow) :slant italic)
     `(tree-sitter-hl-face:number :foreground ,(treesitter-face-fix--get-theme-color 'magenta))
     `(tree-sitter-hl-face:operator :foreground ,(treesitter-face-fix--get-theme-color 'orange))
     `(tree-sitter-hl-face:parameter :foreground ,(treesitter-face-fix--get-theme-color 'fg))
     `(tree-sitter-hl-face:parameter.reference :foreground ,(treesitter-face-fix--get-theme-color 'fg))
     `(tree-sitter-hl-face:property :foreground ,(treesitter-face-fix--get-theme-color 'blue))
     `(tree-sitter-hl-face:punctuation.bracket :foreground ,(treesitter-face-fix--get-theme-color 'fg))
     `(tree-sitter-hl-face:punctuation.delimiter :foreground ,(treesitter-face-fix--get-theme-color 'grey))
     `(tree-sitter-hl-face:repeat :foreground ,(treesitter-face-fix--get-theme-color 'red))
     `(tree-sitter-hl-face:string :foreground ,(treesitter-face-fix--get-theme-color 'cyan))
     `(tree-sitter-hl-face:string.escape :foreground ,(treesitter-face-fix--get-theme-color 'green))
     `(tree-sitter-hl-face:string.regex :foreground ,(treesitter-face-fix--get-theme-color 'green))
     `(tree-sitter-hl-face:string.special :foreground ,(treesitter-face-fix--get-theme-color 'cyan))
     `(tree-sitter-hl-face:type :foreground ,(treesitter-face-fix--get-theme-color 'yellow) :slant italic)
     `(tree-sitter-hl-face:type.builtin :foreground ,(treesitter-face-fix--get-theme-color 'yellow) :slant italic)
     `(tree-sitter-hl-face:type.definition :foreground ,(treesitter-face-fix--get-theme-color 'yellow) :slant italic)
     `(tree-sitter-hl-face:variable :foreground ,(treesitter-face-fix--get-theme-color 'fg))
     `(tree-sitter-hl-face:variable.builtin :foreground ,(treesitter-face-fix--get-theme-color 'magenta) :slant italic)
     `(tree-sitter-hl-face:variable.parameter :foreground ,(treesitter-face-fix--get-theme-color 'fg))
     
     ;; treesit-font-lock:* (same as above but with different names)
     `(treesit-font-lock:annotation :foreground ,(treesitter-face-fix--get-theme-color 'magenta))
     `(treesit-font-lock:attribute :foreground ,(treesitter-face-fix--get-theme-color 'magenta))
     `(treesit-font-lock:boolean :foreground ,(treesitter-face-fix--get-theme-color 'magenta))
     `(treesit-font-lock:character :foreground ,(treesitter-face-fix--get-theme-color 'cyan))
     `(treesit-font-lock:character.special :foreground ,(treesitter-face-fix--get-theme-color 'cyan))
     `(treesit-font-lock:comment :foreground ,(treesitter-face-fix--get-theme-color 'comments))
     `(treesit-font-lock:conditional :foreground ,(treesitter-face-fix--get-theme-color 'red))
     `(treesit-font-lock:constant :foreground ,(treesitter-face-fix--get-theme-color 'fg))
     `(treesit-font-lock:constant.builtin :foreground ,(treesitter-face-fix--get-theme-color 'magenta) :slant italic)
     `(treesit-font-lock:constant.macro :foreground ,(treesitter-face-fix--get-theme-color 'magenta) :slant italic)
     `(treesit-font-lock:constructor :foreground ,(treesitter-face-fix--get-theme-color 'green) :weight bold)
     `(treesit-font-lock:field :foreground ,(treesitter-face-fix--get-theme-color 'blue))
     `(treesit-font-lock:float :foreground ,(treesitter-face-fix--get-theme-color 'magenta))
     `(treesit-font-lock:function :foreground ,(treesitter-face-fix--get-theme-color 'green) :weight bold)
     `(treesit-font-lock:function.call :foreground ,(treesitter-face-fix--get-theme-color 'green) :weight bold)
     `(treesit-font-lock:function.macro :foreground ,(treesitter-face-fix--get-theme-color 'green) :weight bold)
     `(treesit-font-lock:keyword :foreground ,(treesitter-face-fix--get-theme-color 'red))
     `(treesit-font-lock:keyword.conditional :foreground ,(treesitter-face-fix--get-theme-color 'red))
     `(treesit-font-lock:keyword.function :foreground ,(treesitter-face-fix--get-theme-color 'red))
     `(treesit-font-lock:keyword.operator :foreground ,(treesitter-face-fix--get-theme-color 'orange))
     `(treesit-font-lock:keyword.return :foreground ,(treesitter-face-fix--get-theme-color 'red))
     `(treesit-font-lock:label :foreground ,(treesitter-face-fix--get-theme-color 'orange))
     `(treesit-font-lock:method :foreground ,(treesitter-face-fix--get-theme-color 'green) :weight bold)
     `(treesit-font-lock:method.call :foreground ,(treesitter-face-fix--get-theme-color 'green) :weight bold)
     `(treesit-font-lock:namespace :foreground ,(treesitter-face-fix--get-theme-color 'yellow) :slant italic)
     `(treesit-font-lock:number :foreground ,(treesitter-face-fix--get-theme-color 'magenta))
     `(treesit-font-lock:operator :foreground ,(treesitter-face-fix--get-theme-color 'orange))
     `(treesit-font-lock:parameter :foreground ,(treesitter-face-fix--get-theme-color 'fg))
     `(treesit-font-lock:parameter.reference :foreground ,(treesitter-face-fix--get-theme-color 'fg))
     `(treesit-font-lock:property :foreground ,(treesitter-face-fix--get-theme-color 'blue))
     `(treesit-font-lock:punctuation.bracket :foreground ,(treesitter-face-fix--get-theme-color 'fg))
     `(treesit-font-lock:punctuation.delimiter :foreground ,(treesitter-face-fix--get-theme-color 'grey))
     `(treesit-font-lock:repeat :foreground ,(treesitter-face-fix--get-theme-color 'red))
     `(treesit-font-lock:string :foreground ,(treesitter-face-fix--get-theme-color 'cyan))
     `(treesit-font-lock:string.escape :foreground ,(treesitter-face-fix--get-theme-color 'green))
     `(treesit-font-lock:string.regex :foreground ,(treesitter-face-fix--get-theme-color 'green))
     `(treesit-font-lock:string.special :foreground ,(treesitter-face-fix--get-theme-color 'cyan))
     `(treesit-font-lock:type :foreground ,(treesitter-face-fix--get-theme-color 'yellow) :slant italic)
     `(treesit-font-lock:type.builtin :foreground ,(treesitter-face-fix--get-theme-color 'yellow) :slant italic)
     `(treesit-font-lock:type.definition :foreground ,(treesitter-face-fix--get-theme-color 'yellow) :slant italic)
     `(treesit-font-lock:variable :foreground ,(treesitter-face-fix--get-theme-color 'fg))
     `(treesit-font-lock:variable.builtin :foreground ,(treesitter-face-fix--get-theme-color 'magenta) :slant italic)
     `(treesit-font-lock:variable.parameter :foreground ,(treesitter-face-fix--get-theme-color 'fg)))))

(defun treesitter-face-fix--verify-faces ()
  "Verify that treesitter faces have been colored."
  (let ((sample-faces '("tree-sitter-hl-face:keyword"
                        "tree-sitter-hl-face:string"
                        "tree-sitter-hl-face:comment"
                        "tree-sitter-hl-face:variable"
                        "treesit-font-lock:keyword"
                        "treesit-font-lock:string"
                        "treesit-font-lock:comment"
                        "treesit-font-lock:variable")))
    (dolist (face-name sample-faces)
      (let ((face-sym (intern face-name)))
        (when (facep face-sym)
          (let ((fg (face-foreground face-sym nil t)))
            (if fg
                (message "treesitter-face-fix: ✓ %s = %s" face-name fg)
              (message "treesitter-face-fix: ✗ %s has no foreground color" face-name))))))))

(defun treesitter-face-fix--apply-theme-faces (&rest _)
  "Apply treesitter faces after theme loads."
  (message "treesitter-face-fix: Applying treesitter faces for theme...")
  (treesitter-face-fix--create-treesitter-faces)
  
  ;; Apply theme-specific faces based on active theme
  (cond
   ((member 'doom-gruvbox-material custom-enabled-themes)
    (treesitter-face-fix--apply-gruvbox-material-faces)
    (message "treesitter-face-fix: Applied gruvbox-material treesitter faces")
    ;; Verify that faces have colors
    (treesitter-face-fix--verify-faces))
   ((member 'catppuccin custom-enabled-themes)
    ;; Catppuccin doesn't have treesitter faces in theme file
    ;; We'll apply a generic fallback using theme colors
    (message "treesitter-face-fix: Catppuccin theme loaded - no treesitter faces defined in theme"))
   (t
    (message "treesitter-face-fix: Unknown theme - treesitter faces may not be colored"))))

;; Add advice to enable-theme to apply treesitter faces after theme loads
(advice-add 'enable-theme :after #'treesitter-face-fix--apply-theme-faces)

;; Also run once now in case theme is already loaded
(when custom-enabled-themes
  (treesitter-face-fix--apply-theme-faces))

(provide 'treesitter-face-fix)

;;; treesitter-face-fix.el ends here